name: Santa
favicon: null
layout_spectrum: 0.86406
typography_spectrum: 0.2541523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#242635'
    - '#555674'
    - '#949BCF'
    - '#D95258'
  brandStrength: 0
  lightness: 0.09275496
  saturation: 0.7947804
  rhythmicContrast: 0.05842225
purpose: []
