layout_spectrum: 0.9129626
color:
  saturation: 0.7947804
  lightness: 0.09275496
  brandStrength: 0
  brandColors:
    - '#FFFFFF'
    - '#242635'
    - '#555674'
    - '#949BCF'
    - '#D95258'
  rhythmicContrast: 0.05842225
typography_spectrum: 0.2541523
name: Santa
